<a href="https://colab.research.google.com/github/Reaper-X003/Assembly-Codes/blob/main/037_1stlab_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1st day of lab asssignment, completing all the questions as asked**

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns
###

1. Scalar & Array Operations (Redo Section with Your Own Values):

Run the given code with scalar = 3.7 and a new array of at least 6 elements.


Show outputs of all built-in mathematical functions (sin, cos, tan, etc.).


In [ ]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([100,90,80,70,50,20,10])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)


# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)


sin: [-0.50636564  0.89399666 -0.99388865  0.77389068 -0.26237485  0.91294525
 -0.54402111]
cos: [ 0.86231887 -0.44807362 -0.11038724  0.6333192   0.96496603  0.40808206
 -0.83907153]
tan: [-0.58721392 -1.99520041  9.00365495  1.22195992 -0.27190061  2.23716094
  0.64836083]
asin: [1.57079633 1.11976951 0.92729522 0.7753975  0.52359878 0.20135792
 0.10016742]
acos: [0.         0.45102681 0.64350111 0.79539883 1.04719755 1.36943841
 1.47062891]
atan: [1.56079666 1.55968567 1.55829698 1.55651158 1.55079899 1.52083793
 1.47112767]


2. 2×2 Matrix Calculations (Already Done in Class):

Study and understand the example code given for trigonometric, exponential, logarithmic, and rounding operations on a 2×2 matrix.

In [ ]:
# Creating a 2x2 matrix
matrix = np.array([[16, 22], [35, 40]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[16 22]
 [35 40]]

sin:
 [[-0.28790332 -0.00885131]
 [-0.42818267  0.74511316]]

cos:
 [[-0.95765948 -0.99996083]
 [-0.90369221 -0.66693806]]

tan:
 [[ 0.30063224  0.00885166]
 [ 0.47381472 -1.11721493]]

asine:
 [[0.41151685 0.58236424]
 [1.06543582 1.57079633]]

acosine:
 [[1.15927948 0.98843209]
 [0.50536051 0.        ]]

atangent:
 [[1.50837752 1.52537305]
 [1.54223267 1.54580153]]

exp:
 [[8.88611052e+06 3.58491285e+09]
 [1.58601345e+15 2.35385267e+17]]

log (natural):
 [[2.77258872 3.09104245]
 [3.55534806 3.68887945]]

round:
 [[16 22]
 [35 40]]

floor:
 [[16. 22.]
 [35. 40.]]

ceil:
 [[16. 22.]
 [35. 40.]]


3rd Task: Apply the Same Operations on a 3×2 Matrix
Create a 3×2 matrix with custom values.


  1. Perform and display results of:

  2. Trigonometric functions

  3. Exponential & logarithmic functions

  4. Absolute value & square root

  5. Remainder when divided by 2

  6. Rounding (round, floor, ceil)


In [ ]:
# Creating a 3x2 matrix
matrix = np.array([[178, 223], [423, 465], [323,532]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[178 223]
 [423 465]
 [323 532]]

sin:
 [[ 0.87757534  0.05305349]
 [ 0.89791441  0.04427279]
 [ 0.55140153 -0.87760424]]

cos:
 [[-0.47943877 -0.99859167]
 [-0.44017009  0.99901948]
 [-0.83423998 -0.47938586]]

tan:
 [[-1.83042215 -0.05312831]
 [-2.039926    0.04431625]
 [-0.66096273  1.83068446]]

asine:
 [[0.34116637 0.43253417]
 [0.91919352 1.06349786]
 [0.6524599  1.57079633]]

acosine:
 [[1.22962996 1.13826216]
 [0.6516028  0.50729846]
 [0.91833643 0.        ]]

atangent:
 [[1.56517841 1.56631205]
 [1.56843227 1.56864579]
 [1.56770036 1.56891663]]

exp:
 [[2.01566233e+077 7.04156941e+096]
 [5.08821958e+183 8.84981282e+201]
 [1.89285634e+140 1.10831796e+231]]

log (natural):
 [[5.18178355 5.40717177]
 [6.04737218 6.14203741]
 [5.77765232 6.27664349]]

abs:
 [[178 223]
 [423 465]
 [323 532]]

sqrt:
 [[13.34166406 14.93318452]
 [20.5669638  21.56385865]
 [17.97220076 23.06512519]]

rem (remainder when divided by 2):
 [[0 1]
 [1 1]
 [1 0]]

round:
 [[178 223]
 [423 465]
 [3

4. Vector Functions
Understand the operations on the 1D vector shown in the notebook.


Task: Perform Same Operations on a 2×3 Matrix
Your 2×3 matrix can have float values (e.g., 2.1, 4.7…).


Implement and display:


1. Max & Min (with indices)


2. Vector length


3. Sorted version (both row-wise descending and entire matrix descending)


4. Sum, Product


5. Median, Mean, Standard Deviation


📌 Hint: Use np.sort() with axis=1 for row-wise sorting. Use .flatten() for entire matrix sorting.


In [8]:
# Sample vector (1D array)
#2X3 matrix
vec = np.array([[3.5, 1.1, 3.2], [2.4, 3.5, 3.3]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 2. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 3. Sorting in ascending order (both row-wise descending and entire matrix descending)
sorted_vec = np.sort(vec)
sorted_row = np.sort(vec, axis = 1) [:,::-1]
sorted_entire = np.sort(vec.flatten())[::-1]


# 4. Sum of elements
sum_values = np.sum(vec)

# Product of elements
prod_values = np.prod(vec)

# 5. Median value
median_value = np.median(vec)

# Mean value
mean_value = np.mean(vec)

# Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sorted Row-wise vector:", sorted_row)
print("Sorted Entire vector:", sorted_entire)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 3.5 at index 0
Min value: 1.1 at index 1
Length of vector: 2
Sorted vector: [[1.1 3.2 3.5]
 [2.4 3.3 3.5]]
Sorted Row-wise vector: [[3.5 3.2 1.1]
 [3.5 3.3 2.4]]
Sorted Entire vector: [3.5 3.5 3.3 3.2 2.4 1.1]
Sum of elements: 17.0
Product of elements: 341.5104
Median value: 3.25
Mean value: 2.8333333333333335
Standard deviation: 0.8595864638818418
